<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework />
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EncDotNet.S100.Renderers.Mapsui.Avalonia.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="Mapsui.Avalonia12" />
    <PackageReference Include="Mapsui.Rendering.Skia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EncDotNet.S100.Core\EncDotNet.S100.Core.csproj" />
    <ProjectReference Include="..\EncDotNet.S100.Renderers.Mapsui\EncDotNet.S100.Renderers.Mapsui.csproj" />
  </ItemGroup>

</Project>
