using System.Globalization;
using System.Resources;

namespace EncDotNet.S100.Viewer.Resources;

/// <summary>
/// Strongly-typed accessor for the viewer's UI strings (see Strings.resx).
/// Every user-visible string in the viewer is exposed here so the UI can be
/// localized by adding satellite resources without touching XAML or code.
/// </summary>
/// <remarks>
/// Hand-written rather than generated by ResXFileCodeGenerator so that
/// <c>dotnet build</c> alone (no Visual Studio designer) keeps the file in
/// sync. When adding a new key:
/// <list type="number">
///   <item>Add the <c>&lt;data&gt;</c> entry to <c>Strings.resx</c>.</item>
///   <item>Add a matching property below.</item>
/// </list>
/// </remarks>
internal static class Strings
{
    private static readonly ResourceManager ResourceManager =
        new("EncDotNet.S100.Viewer.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The current UI culture used to look up strings.</summary>
    public static CultureInfo Culture { get; set; } = CultureInfo.CurrentUICulture;

    private static string Get(string name) =>
        ResourceManager.GetString(name, Culture) ?? name;

    // Window
    public static string Window_Title => Get(nameof(Window_Title));

    // Activity / pane titles
    public static string Pane_FeatureCatalogues => Get(nameof(Pane_FeatureCatalogues));
    public static string Pane_PortrayalCatalogues => Get(nameof(Pane_PortrayalCatalogues));
    public static string Pane_Datasets => Get(nameof(Pane_Datasets));
    public static string Pane_DatasetOpacity => Get(nameof(Pane_DatasetOpacity));
    public static string Pane_DatasetSelectPlaceholder => Get(nameof(Pane_DatasetSelectPlaceholder));
    public static string Pane_DatasetField_Spec => Get(nameof(Pane_DatasetField_Spec));
    public static string Pane_DatasetField_Time => Get(nameof(Pane_DatasetField_Time));
    public static string Pane_DatasetTab_Dataset => Get(nameof(Pane_DatasetTab_Dataset));
    public static string Pane_DatasetTab_Layers => Get(nameof(Pane_DatasetTab_Layers));
    public static string Pane_DatasetTab_NoLayers => Get(nameof(Pane_DatasetTab_NoLayers));
    public static string Pane_DatasetTab_Validation => Get(nameof(Pane_DatasetTab_Validation));
    public static string Pane_Validation_NoFindings => Get(nameof(Pane_Validation_NoFindings));
    public static string Pane_Validation_NoRulePack => Get(nameof(Pane_Validation_NoRulePack));
    public static string Pane_Validation_CountsSummaryFormat => Get(nameof(Pane_Validation_CountsSummaryFormat));
    public static string Pane_Validation_RelatedFeatureFormat => Get(nameof(Pane_Validation_RelatedFeatureFormat));
    public static string Pane_Validation_Severity_Error => Get(nameof(Pane_Validation_Severity_Error));
    public static string Pane_Validation_Severity_Warning => Get(nameof(Pane_Validation_Severity_Warning));
    public static string Pane_Validation_Severity_Info => Get(nameof(Pane_Validation_Severity_Info));
    public static string Tooltip_ValidationBadge => Get(nameof(Tooltip_ValidationBadge));
    public static string Tooltip_FindingZoomTo => Get(nameof(Tooltip_FindingZoomTo));
    public static string Tooltip_FindingNoSpatialLocation => Get(nameof(Tooltip_FindingNoSpatialLocation));
    public static string Pane_Catalog => Get(nameof(Pane_Catalog));
    public static string Pane_Settings => Get(nameof(Pane_Settings));
    public static string Pane_Search => Get(nameof(Pane_Search));
    public static string Pane_LayerStack => Get(nameof(Pane_LayerStack));

    // Layer Stack panel (PR-L3)
    public static string LayerStack_PanelTitle => Get(nameof(LayerStack_PanelTitle));
    public static string LayerStack_ShowEmptyPlanes => Get(nameof(LayerStack_ShowEmptyPlanes));
    public static string LayerStack_EmptyPlane_Placeholder => Get(nameof(LayerStack_EmptyPlane_Placeholder));
    public static string LayerStack_ActiveTooltip => Get(nameof(LayerStack_ActiveTooltip));
    public static string LayerStack_VisibilityVsActive_HelpText => Get(nameof(LayerStack_VisibilityVsActive_HelpText));
    public static string LayerStack_ChildCountFormat => Get(nameof(LayerStack_ChildCountFormat));
    public static string LayerStack_PriorityFormat => Get(nameof(LayerStack_PriorityFormat));
    public static string LayerStack_Plane_BaseChartUnder => Get(nameof(LayerStack_Plane_BaseChartUnder));
    public static string LayerStack_Plane_Bathymetry => Get(nameof(LayerStack_Plane_Bathymetry));
    public static string LayerStack_Plane_OnDemandSurface => Get(nameof(LayerStack_Plane_OnDemandSurface));
    public static string LayerStack_Plane_BaseChartOver => Get(nameof(LayerStack_Plane_BaseChartOver));
    public static string LayerStack_Plane_OtherChartOverlays => Get(nameof(LayerStack_Plane_OtherChartOverlays));
    public static string LayerStack_Plane_CautionsAndWarnings => Get(nameof(LayerStack_Plane_CautionsAndWarnings));
    public static string LayerStack_Plane_DynamicArrows => Get(nameof(LayerStack_Plane_DynamicArrows));
    public static string LayerStack_Plane_MarinerOverlay => Get(nameof(LayerStack_Plane_MarinerOverlay));
    public static string LayerStack_Plane_EcdisAlerts => Get(nameof(LayerStack_Plane_EcdisAlerts));

    // Search
    public static string Search_Placeholder => Get(nameof(Search_Placeholder));
    public static string Search_NoResults => Get(nameof(Search_NoResults));
    public static string Search_ResultsFooter => Get(nameof(Search_ResultsFooter));
    public static string Search_TruncatedFooter => Get(nameof(Search_TruncatedFooter));

    // Tooltips
    public static string Tooltip_ToggleTheme => Get(nameof(Tooltip_ToggleTheme));
    public static string Tooltip_Settings => Get(nameof(Tooltip_Settings));
    public static string Tooltip_FeatureCatalogues => Get(nameof(Tooltip_FeatureCatalogues));
    public static string Tooltip_PortrayalCatalogues => Get(nameof(Tooltip_PortrayalCatalogues));
    public static string Tooltip_Datasets => Get(nameof(Tooltip_Datasets));
    public static string Tooltip_Catalog => Get(nameof(Tooltip_Catalog));
    public static string Tooltip_LayerStack => Get(nameof(Tooltip_LayerStack));
    public static string Tooltip_PickMode => Get(nameof(Tooltip_PickMode));
    public static string Tooltip_ZoomIn => Get(nameof(Tooltip_ZoomIn));
    public static string Tooltip_ZoomOut => Get(nameof(Tooltip_ZoomOut));
    public static string Tooltip_ZoomToExtent => Get(nameof(Tooltip_ZoomToExtent));
    public static string Tooltip_ClosePickPanel => Get(nameof(Tooltip_ClosePickPanel));
    public static string Tooltip_SelectHit => Get(nameof(Tooltip_SelectHit));
    public static string Tooltip_FollowReference => Get(nameof(Tooltip_FollowReference));
    public static string Tooltip_Search => Get(nameof(Tooltip_Search));
    public static string Tooltip_ClearSearch => Get(nameof(Tooltip_ClearSearch));
    public static string Tooltip_OpenSearchResult => Get(nameof(Tooltip_OpenSearchResult));
    public static string Tooltip_CloseTimelinePanel => Get(nameof(Tooltip_CloseTimelinePanel));
    public static string Tooltip_AddFeatureCatalogue => Get(nameof(Tooltip_AddFeatureCatalogue));
    public static string Tooltip_AddPortrayalCatalogue => Get(nameof(Tooltip_AddPortrayalCatalogue));
    public static string Tooltip_OpenDataset => Get(nameof(Tooltip_OpenDataset));
    public static string Tooltip_RemoveCatalogue => Get(nameof(Tooltip_RemoveCatalogue));
    public static string Tooltip_RemoveDataset => Get(nameof(Tooltip_RemoveDataset));
    public static string Tooltip_ToggleDatasetVisibility => Get(nameof(Tooltip_ToggleDatasetVisibility));
    public static string Tooltip_DatasetOpacity => Get(nameof(Tooltip_DatasetOpacity));
    public static string Tooltip_MoveDatasetUp => Get(nameof(Tooltip_MoveDatasetUp));
    public static string Tooltip_MoveDatasetDown => Get(nameof(Tooltip_MoveDatasetDown));
    public static string Menu_BringDatasetToFront => Get(nameof(Menu_BringDatasetToFront));
    public static string Menu_SendDatasetToBack => Get(nameof(Menu_SendDatasetToBack));
    public static string Menu_MoveDatasetUp => Get(nameof(Menu_MoveDatasetUp));
    public static string Menu_MoveDatasetDown => Get(nameof(Menu_MoveDatasetDown));
    public static string SubLayer_S111_ColorBand => Get(nameof(SubLayer_S111_ColorBand));
    public static string SubLayer_S111_Arrows => Get(nameof(SubLayer_S111_Arrows));
    public static string Tooltip_ToggleSubLayerVisibility => Get(nameof(Tooltip_ToggleSubLayerVisibility));
    public static string Tooltip_SubLayerOpacity => Get(nameof(Tooltip_SubLayerOpacity));
    public static string Tooltip_ExpandSubLayers => Get(nameof(Tooltip_ExpandSubLayers));
    public static string Pane_SubLayers => Get(nameof(Pane_SubLayers));
    public static string Pane_ExchangeSetHeader_Producer => Get(nameof(Pane_ExchangeSetHeader_Producer));
    public static string Pane_ExchangeSetHeader_Issued => Get(nameof(Pane_ExchangeSetHeader_Issued));
    public static string Pane_ExchangeSetHeader_Count => Get(nameof(Pane_ExchangeSetHeader_Count));
    public static string Pane_ExchangeSetHeader_Unsupported => Get(nameof(Pane_ExchangeSetHeader_Unsupported));
    public static string Tooltip_CloseExchangeSet => Get(nameof(Tooltip_CloseExchangeSet));
    public static string Tooltip_SignatureVerified => Get(nameof(Tooltip_SignatureVerified));
    public static string Tooltip_SignatureUnsigned => Get(nameof(Tooltip_SignatureUnsigned));
    public static string Tooltip_SignatureInvalid => Get(nameof(Tooltip_SignatureInvalid));
    public static string Tooltip_SignatureUntrusted => Get(nameof(Tooltip_SignatureUntrusted));
    public static string Tooltip_SignatureMixed => Get(nameof(Tooltip_SignatureMixed));
    public static string Tooltip_SignatureChecking => Get(nameof(Tooltip_SignatureChecking));
    public static string Tooltip_SignatureError => Get(nameof(Tooltip_SignatureError));
    public static string Tooltip_ShowAllDatasets => Get(nameof(Tooltip_ShowAllDatasets));
    public static string Tooltip_HideAllDatasets => Get(nameof(Tooltip_HideAllDatasets));
    public static string Menu_IsolateDataset => Get(nameof(Menu_IsolateDataset));
    public static string Tooltip_ResetDatasetOpacity => Get(nameof(Tooltip_ResetDatasetOpacity));
    public static string Tooltip_TimelineSlider => Get(nameof(Tooltip_TimelineSlider));
    public static string Tooltip_TimelinePreviousStep => Get(nameof(Tooltip_TimelinePreviousStep));
    public static string Tooltip_TimelineNextStep => Get(nameof(Tooltip_TimelineNextStep));
    public static string Tooltip_MouseLatLon => Get(nameof(Tooltip_MouseLatLon));

    // Buttons / actions
    public static string Button_OpenDataset => Get(nameof(Button_OpenDataset));
    public static string Button_AddFeatureCatalogue => Get(nameof(Button_AddFeatureCatalogue));
    public static string Button_AddPortrayalCatalogue => Get(nameof(Button_AddPortrayalCatalogue));

    // Native menu
    public static string Menu_File => Get(nameof(Menu_File));
    public static string Menu_OpenDataset => Get(nameof(Menu_OpenDataset));
    public static string Menu_OpenExchangeSet => Get(nameof(Menu_OpenExchangeSet));
    public static string Menu_OpenExchangeSetZip => Get(nameof(Menu_OpenExchangeSetZip));
    public static string Menu_OpenRecent => Get(nameof(Menu_OpenRecent));
    public static string Menu_NoRecentDatasets => Get(nameof(Menu_NoRecentDatasets));
    public static string Menu_ClearRecentlyOpened => Get(nameof(Menu_ClearRecentlyOpened));
    public static string Menu_View => Get(nameof(Menu_View));
    public static string Menu_Appearance => Get(nameof(Menu_Appearance));
    public static string Menu_PrimarySideBar => Get(nameof(Menu_PrimarySideBar));
    public static string Menu_StatusBar => Get(nameof(Menu_StatusBar));
    public static string Menu_Timeline => Get(nameof(Menu_Timeline));
    public static string Menu_PickReport => Get(nameof(Menu_PickReport));
    public static string Menu_PickMode => Get(nameof(Menu_PickMode));

    // File picker
    public static string FilePicker_OpenDatasetTitle => Get(nameof(FilePicker_OpenDatasetTitle));
    public static string FilePicker_S100DatasetsType => Get(nameof(FilePicker_S100DatasetsType));
    public static string FilePicker_ExchangeSetFolderTitle => Get(nameof(FilePicker_ExchangeSetFolderTitle));
    public static string FilePicker_ExchangeSetZipTitle => Get(nameof(FilePicker_ExchangeSetZipTitle));
    public static string FilePicker_ExchangeSetZipType => Get(nameof(FilePicker_ExchangeSetZipType));

    // Catalogue list
    public static string Catalogue_BuiltInLabel => Get(nameof(Catalogue_BuiltInLabel));

    // Catalog (S-128) panel
    public static string Catalog_EmptyMessage => Get(nameof(Catalog_EmptyMessage));
    public static string Catalog_SelectEntryPlaceholder => Get(nameof(Catalog_SelectEntryPlaceholder));
    public static string Catalog_NotForNavigation => Get(nameof(Catalog_NotForNavigation));
    public static string Catalog_Field_Spec => Get(nameof(Catalog_Field_Spec));
    public static string Catalog_Field_Edition => Get(nameof(Catalog_Field_Edition));
    public static string Catalog_Field_Update => Get(nameof(Catalog_Field_Update));
    public static string Catalog_Field_Issued => Get(nameof(Catalog_Field_Issued));
    public static string Catalog_Field_Updated => Get(nameof(Catalog_Field_Updated));
    public static string Catalog_Field_Coverage => Get(nameof(Catalog_Field_Coverage));
    public static string Catalog_Field_NorthEast => Get(nameof(Catalog_Field_NorthEast));
    public static string Catalog_Field_SouthWest => Get(nameof(Catalog_Field_SouthWest));
    public static string Catalog_SourceProperties => Get(nameof(Catalog_SourceProperties));

    // Pick (Object Information) panel
    public static string Pick_PanelTitle => Get(nameof(Pick_PanelTitle));
    public static string PickReport_EmptyState => Get(nameof(PickReport_EmptyState));
    public static string Pick_IdLabel => Get(nameof(Pick_IdLabel));
    public static string Pick_SpecFormat => Get(nameof(Pick_SpecFormat));
    public static string Pick_SourceFormat => Get(nameof(Pick_SourceFormat));
    public static string Pick_AttributesHeading => Get(nameof(Pick_AttributesHeading));
    public static string Pick_NoAttributes => Get(nameof(Pick_NoAttributes));
    public static string Pick_HitListHeader => Get(nameof(Pick_HitListHeader));
    public static string Pick_HitListItemFormat => Get(nameof(Pick_HitListItemFormat));
    public static string Pick_ReferencesHeader => Get(nameof(Pick_ReferencesHeader));
    public static string Pick_ReferenceItemFormat => Get(nameof(Pick_ReferenceItemFormat));

    // Pick panel: station time-series chart
    public static string Pick_Chart_Title_WaterLevel => Get(nameof(Pick_Chart_Title_WaterLevel));
    public static string Pick_Chart_Title_SurfaceCurrentSpeed => Get(nameof(Pick_Chart_Title_SurfaceCurrentSpeed));
    public static string Pick_Chart_Title_SurfaceCurrentDirection => Get(nameof(Pick_Chart_Title_SurfaceCurrentDirection));
    public static string Pick_Chart_Axis_Time => Get(nameof(Pick_Chart_Axis_Time));
    public static string Pick_Chart_Axis_HeightMetres => Get(nameof(Pick_Chart_Axis_HeightMetres));
    public static string Pick_Chart_Axis_SpeedMetresPerSecond => Get(nameof(Pick_Chart_Axis_SpeedMetresPerSecond));
    public static string Pick_Chart_Axis_DirectionDegrees => Get(nameof(Pick_Chart_Axis_DirectionDegrees));
    public static string Pick_Chart_NowMarker => Get(nameof(Pick_Chart_NowMarker));
    public static string Pick_Chart_NoSamples => Get(nameof(Pick_Chart_NoSamples));
    public static string Pick_Chart_StationAttributes => Get(nameof(Pick_Chart_StationAttributes));

    // Settings
    public static string Settings_Heading => Get(nameof(Settings_Heading));
    public static string Settings_AccentColor => Get(nameof(Settings_AccentColor));
    public static string Settings_ColorProfile => Get(nameof(Settings_ColorProfile));
    public static string Settings_ColorProfile_Help => Get(nameof(Settings_ColorProfile_Help));
    public static string Settings_SymbolScale => Get(nameof(Settings_SymbolScale));
    public static string Settings_SymbolScale_Help => Get(nameof(Settings_SymbolScale_Help));
    public static string Settings_TextScale => Get(nameof(Settings_TextScale));
    public static string Settings_TextScale_Help => Get(nameof(Settings_TextScale_Help));
    public static string Settings_DistanceUnits => Get(nameof(Settings_DistanceUnits));
    public static string Settings_DistanceUnits_Help => Get(nameof(Settings_DistanceUnits_Help));
    public static string Settings_TimeFormat_Label => Get(nameof(Settings_TimeFormat_Label));
    public static string Settings_TimeFormat_Tooltip => Get(nameof(Settings_TimeFormat_Tooltip));
    public static string Settings_TimeFormat_Local => Get(nameof(Settings_TimeFormat_Local));
    public static string Settings_TimeFormat_Utc => Get(nameof(Settings_TimeFormat_Utc));
    public static string Time_Utc_Suffix => Get(nameof(Time_Utc_Suffix));

    // Mariner settings (S-100 Part 9 §4.2)
    public static string Settings_MarinerSection => Get(nameof(Settings_MarinerSection));
    public static string Settings_MarinerSection_Help => Get(nameof(Settings_MarinerSection_Help));
    public static string Settings_DepthUnit => Get(nameof(Settings_DepthUnit));
    public static string Settings_DepthUnit_Help => Get(nameof(Settings_DepthUnit_Help));
    public static string DepthUnit_Metres => Get(nameof(DepthUnit_Metres));
    public static string DepthUnit_Feet => Get(nameof(DepthUnit_Feet));
    public static string DepthUnit_FathomsFeet => Get(nameof(DepthUnit_FathomsFeet));
    public static string DepthUnit_Fathoms => Get(nameof(DepthUnit_Fathoms));
    public static string Settings_SafetyContour => Get(nameof(Settings_SafetyContour));
    public static string Tooltip_SafetyContour => Get(nameof(Tooltip_SafetyContour));
    public static string Settings_SafetyDepth => Get(nameof(Settings_SafetyDepth));
    public static string Tooltip_SafetyDepth => Get(nameof(Tooltip_SafetyDepth));
    public static string Settings_ShallowContour => Get(nameof(Settings_ShallowContour));
    public static string Tooltip_ShallowContour => Get(nameof(Tooltip_ShallowContour));
    public static string Settings_DeepContour => Get(nameof(Settings_DeepContour));
    public static string Tooltip_DeepContour => Get(nameof(Tooltip_DeepContour));
    public static string Settings_FourShades => Get(nameof(Settings_FourShades));
    public static string Tooltip_FourShades => Get(nameof(Tooltip_FourShades));
    public static string Settings_ShallowWaterDangers => Get(nameof(Settings_ShallowWaterDangers));
    public static string Tooltip_ShallowWaterDangers => Get(nameof(Tooltip_ShallowWaterDangers));
    public static string Settings_PlainBoundaries => Get(nameof(Settings_PlainBoundaries));
    public static string Tooltip_PlainBoundaries => Get(nameof(Tooltip_PlainBoundaries));
    public static string Settings_SimplifiedSymbols => Get(nameof(Settings_SimplifiedSymbols));
    public static string Tooltip_SimplifiedSymbols => Get(nameof(Tooltip_SimplifiedSymbols));
    public static string Settings_FullLightLines => Get(nameof(Settings_FullLightLines));
    public static string Tooltip_FullLightLines => Get(nameof(Tooltip_FullLightLines));
    public static string Settings_RadarOverlay => Get(nameof(Settings_RadarOverlay));
    public static string Tooltip_RadarOverlay => Get(nameof(Tooltip_RadarOverlay));
    public static string Settings_IgnoreScaleMinimum => Get(nameof(Settings_IgnoreScaleMinimum));
    public static string Tooltip_IgnoreScaleMinimum => Get(nameof(Tooltip_IgnoreScaleMinimum));
    public static string Settings_NationalLanguage => Get(nameof(Settings_NationalLanguage));
    public static string Tooltip_NationalLanguage => Get(nameof(Tooltip_NationalLanguage));
    public static string Settings_NationalLanguage_Default => Get(nameof(Settings_NationalLanguage_Default));
    public static string Language_System => Get(nameof(Language_System));
    public static string Status_MarinerSettingsApplied => Get(nameof(Status_MarinerSettingsApplied));

    // Distance unit display names
    public static string DistanceUnit_Metric => Get(nameof(DistanceUnit_Metric));
    public static string DistanceUnit_Miles => Get(nameof(DistanceUnit_Miles));
    public static string DistanceUnit_NauticalMiles => Get(nameof(DistanceUnit_NauticalMiles));

    // Palette display names
    public static string Palette_Day => Get(nameof(Palette_Day));
    public static string Palette_Dusk => Get(nameof(Palette_Dusk));
    public static string Palette_Night => Get(nameof(Palette_Night));

    // Status messages
    public static string Status_UnrecognizedFileType => Get(nameof(Status_UnrecognizedFileType));
    public static string Status_SelectPortrayalCatalogue => Get(nameof(Status_SelectPortrayalCatalogue));
    public static string Status_LoadingFile => Get(nameof(Status_LoadingFile));
    public static string Status_Error => Get(nameof(Status_Error));
    public static string Status_RenderingTimeStep => Get(nameof(Status_RenderingTimeStep));
    public static string Status_RenderingAtTime => Get(nameof(Status_RenderingAtTime));
    public static string Status_SwitchingPalette => Get(nameof(Status_SwitchingPalette));
    public static string Status_PaletteApplied => Get(nameof(Status_PaletteApplied));
    public static string Status_FeatureNoDetails => Get(nameof(Status_FeatureNoDetails));
    public static string Status_FeatureSummary => Get(nameof(Status_FeatureSummary));
    public static string Status_FeatureSummaryWithMore => Get(nameof(Status_FeatureSummaryWithMore));
    public static string Status_FeatureRefNotFound => Get(nameof(Status_FeatureRefNotFound));
    public static string Status_FileNoLongerExists => Get(nameof(Status_FileNoLongerExists));
    public static string Status_ExchangeSetLoading => Get(nameof(Status_ExchangeSetLoading));
    public static string Status_ExchangeSetLoaded => Get(nameof(Status_ExchangeSetLoaded));
    public static string Status_ExchangeSetLoadedWithErrors => Get(nameof(Status_ExchangeSetLoadedWithErrors));
    public static string Status_ExchangeSetFailed => Get(nameof(Status_ExchangeSetFailed));
    public static string Status_ExchangeSetCatalogNotFound => Get(nameof(Status_ExchangeSetCatalogNotFound));
    public static string Status_ExchangeSetUnsupportedSpec => Get(nameof(Status_ExchangeSetUnsupportedSpec));
    public static string Status_ExchangeSetCancelled => Get(nameof(Status_ExchangeSetCancelled));

    // Exchange-set progress overlay (es3-progress)
    public static string Progress_ExchangeSetTitle => Get(nameof(Progress_ExchangeSetTitle));
    public static string Progress_ExchangeSetCounter => Get(nameof(Progress_ExchangeSetCounter));
    public static string Progress_ExchangeSetCancel => Get(nameof(Progress_ExchangeSetCancel));
    public static string Banner_ExchangeSetPartial => Get(nameof(Banner_ExchangeSetPartial));
    public static string Banner_ExchangeSetFailed => Get(nameof(Banner_ExchangeSetFailed));
    public static string Banner_Dismiss => Get(nameof(Banner_Dismiss));

    // Dataset entry
    public static string DatasetEntry_CurrentTimeFormat => Get(nameof(DatasetEntry_CurrentTimeFormat));

    // Timeline panel
    public static string TimelinePanel_Title => Get(nameof(TimelinePanel_Title));
    public static string TimelinePanel_Range => Get(nameof(TimelinePanel_Range));
    public static string TimelinePanel_NoData => Get(nameof(TimelinePanel_NoData));
    public static string TimelinePanel_EmptyTitle => Get(nameof(TimelinePanel_EmptyTitle));
    public static string TimelinePanel_EmptyDescription => Get(nameof(TimelinePanel_EmptyDescription));

    // Measure Mode
    public static string Tooltip_MeasureMode => Get(nameof(Tooltip_MeasureMode));

    // ECDIS Display Controls
    public static string Pane_EcdisDisplay => Get(nameof(Pane_EcdisDisplay));
    public static string Tooltip_EcdisDisplay => Get(nameof(Tooltip_EcdisDisplay));
    public static string Toolbar_DisplayFormat => Get(nameof(Toolbar_DisplayFormat));
    public static string Tooltip_DisplayMode => Get(nameof(Tooltip_DisplayMode));
    public static string DisplayCategory_DisplayBase => Get(nameof(DisplayCategory_DisplayBase));
    public static string DisplayCategory_Standard => Get(nameof(DisplayCategory_Standard));
    public static string DisplayCategory_OtherInformation => Get(nameof(DisplayCategory_OtherInformation));
    public static string DisplayCategory_All => Get(nameof(DisplayCategory_All));
    public static string Button_ResetOverrides => Get(nameof(Button_ResetOverrides));
    public static string Tooltip_ResetOverrides => Get(nameof(Tooltip_ResetOverrides));
    public static string Button_ResetAllOverrides => Get(nameof(Button_ResetAllOverrides));
    public static string Tooltip_ResetAllOverrides => Get(nameof(Tooltip_ResetAllOverrides));
    public static string EcdisPanel_NoSpecs => Get(nameof(EcdisPanel_NoSpecs));
    public static string EcdisPanel_OverrideCountFormat => Get(nameof(EcdisPanel_OverrideCountFormat));
    public static string EcdisPanel_CategoryHeader => Get(nameof(EcdisPanel_CategoryHeader));
    public static string EcdisPanel_SynthesizedLabelFormat => Get(nameof(EcdisPanel_SynthesizedLabelFormat));
    public static string Menu_MeasureMode => Get(nameof(Menu_MeasureMode));
    public static string Status_MeasureLeg => Get(nameof(Status_MeasureLeg));
    public static string Status_MeasureTotal => Get(nameof(Status_MeasureTotal));
    public static string Status_MeasureNoData => Get(nameof(Status_MeasureNoData));
    public static string Status_MeasureLegLabel => Get(nameof(Status_MeasureLegLabel));

    // ECDIS Display Planes
    public static string EcdisPanel_DisplayPlanesHeader => Get(nameof(EcdisPanel_DisplayPlanesHeader));
    public static string DisplayPlane_UnderRadar => Get(nameof(DisplayPlane_UnderRadar));
    public static string DisplayPlane_OverRadar => Get(nameof(DisplayPlane_OverRadar));
    public static string Tooltip_DisplayPlane_UnderRadar => Get(nameof(Tooltip_DisplayPlane_UnderRadar));
    public static string Tooltip_DisplayPlane_OverRadar => Get(nameof(Tooltip_DisplayPlane_OverRadar));

    // Text group toolbar pill
    public static string Toolbar_Text => Get(nameof(Toolbar_Text));
    public static string Tooltip_TextGroupPill => Get(nameof(Tooltip_TextGroupPill));
    public static string TextGroup_Important => Get(nameof(TextGroup_Important));
    public static string TextGroup_Other => Get(nameof(TextGroup_Other));
    public static string TextGroup_All => Get(nameof(TextGroup_All));

    // Toast notification titles
    public static string Toast_Error => Get(nameof(Toast_Error));
    public static string Toast_Warning => Get(nameof(Toast_Warning));
    public static string Toast_Success => Get(nameof(Toast_Success));
    public static string Toast_Info => Get(nameof(Toast_Info));
    public static string Toast_ExchangeSetLoaded => Get(nameof(Toast_ExchangeSetLoaded));
    public static string Toast_ExchangeSetFailed => Get(nameof(Toast_ExchangeSetFailed));
    public static string Toast_DatasetError => Get(nameof(Toast_DatasetError));
    public static string Toast_Loading => Get(nameof(Toast_Loading));
    public static string Toast_DatasetCancelled => Get(nameof(Toast_DatasetCancelled));
    public static string Toast_Cancel => Get(nameof(Toast_Cancel));
    public static string Toast_ExchangeSetLoading => Get(nameof(Toast_ExchangeSetLoading));

    // MCP server
    public static string Status_McpRunning => Get(nameof(Status_McpRunning));
    public static string Tooltip_McpEndpoint => Get(nameof(Tooltip_McpEndpoint));
    public static string Tooltip_McpLoopback => Get(nameof(Tooltip_McpLoopback));
    public static string Settings_McpSection => Get(nameof(Settings_McpSection));
    public static string Settings_McpEnabled => Get(nameof(Settings_McpEnabled));
    public static string Settings_McpEnabledTooltip => Get(nameof(Settings_McpEnabledTooltip));
    public static string Settings_McpPort => Get(nameof(Settings_McpPort));
    public static string Settings_McpPortTooltip => Get(nameof(Settings_McpPortTooltip));
    public static string Settings_McpPort_ResetToAuto => Get(nameof(Settings_McpPort_ResetToAuto));
    public static string Settings_McpPort_ResetToAutoTooltip => Get(nameof(Settings_McpPort_ResetToAutoTooltip));
    public static string Toast_McpPortConflictTitle => Get(nameof(Toast_McpPortConflictTitle));
    public static string Toast_McpPortConflictBody => Get(nameof(Toast_McpPortConflictBody));
    public static string Toast_McpPortFindAnother => Get(nameof(Toast_McpPortFindAnother));
    public static string Toast_McpPortReassignedTitle => Get(nameof(Toast_McpPortReassignedTitle));
    public static string Toast_McpPortReassignedBody => Get(nameof(Toast_McpPortReassignedBody));

    // Load-failure toast
    public static string Toast_DatasetErrorTitle => Get(nameof(Toast_DatasetErrorTitle));
    public static string LoadFailureToast_NotSupportedBody => Get(nameof(LoadFailureToast_NotSupportedBody));
    public static string LoadFailureToast_SchemaBody => Get(nameof(LoadFailureToast_SchemaBody));
    public static string LoadFailureToast_CopyDetails => Get(nameof(LoadFailureToast_CopyDetails));
}
