using System.Globalization;
using System.Resources;

namespace EncDotNet.S100.Viewer.Resources;

/// <summary>
/// Strongly-typed accessor for the viewer's UI strings (see Strings.resx).
/// Every user-visible string in the viewer is exposed here so the UI can be
/// localized by adding satellite resources without touching XAML or code.
/// </summary>
/// <remarks>
/// Hand-written rather than generated by ResXFileCodeGenerator so that
/// <c>dotnet build</c> alone (no Visual Studio designer) keeps the file in
/// sync. When adding a new key:
/// <list type="number">
///   <item>Add the <c>&lt;data&gt;</c> entry to <c>Strings.resx</c>.</item>
///   <item>Add a matching property below.</item>
/// </list>
/// </remarks>
internal static class Strings
{
    private static readonly ResourceManager ResourceManager =
        new("EncDotNet.S100.Viewer.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The current UI culture used to look up strings.</summary>
    public static CultureInfo Culture { get; set; } = CultureInfo.CurrentUICulture;

    private static string Get(string name) =>
        ResourceManager.GetString(name, Culture) ?? name;

    // Window
    public static string Window_Title => Get(nameof(Window_Title));

    // Activity / pane titles
    public static string Pane_FeatureCatalogues => Get(nameof(Pane_FeatureCatalogues));
    public static string Pane_PortrayalCatalogues => Get(nameof(Pane_PortrayalCatalogues));
    public static string Pane_Datasets => Get(nameof(Pane_Datasets));
    public static string Pane_DatasetOpacity => Get(nameof(Pane_DatasetOpacity));
    public static string Pane_DatasetSelectPlaceholder => Get(nameof(Pane_DatasetSelectPlaceholder));
    public static string Pane_DatasetField_Spec => Get(nameof(Pane_DatasetField_Spec));
    public static string Pane_DatasetField_Time => Get(nameof(Pane_DatasetField_Time));
    public static string Pane_DatasetTab_Dataset => Get(nameof(Pane_DatasetTab_Dataset));
    public static string Pane_DatasetTab_Layers => Get(nameof(Pane_DatasetTab_Layers));
    public static string Pane_DatasetTab_NoLayers => Get(nameof(Pane_DatasetTab_NoLayers));
    public static string Pane_Catalog => Get(nameof(Pane_Catalog));
    public static string Pane_Settings => Get(nameof(Pane_Settings));

    // Tooltips
    public static string Tooltip_ToggleTheme => Get(nameof(Tooltip_ToggleTheme));
    public static string Tooltip_Settings => Get(nameof(Tooltip_Settings));
    public static string Tooltip_FeatureCatalogues => Get(nameof(Tooltip_FeatureCatalogues));
    public static string Tooltip_PortrayalCatalogues => Get(nameof(Tooltip_PortrayalCatalogues));
    public static string Tooltip_Datasets => Get(nameof(Tooltip_Datasets));
    public static string Tooltip_Catalog => Get(nameof(Tooltip_Catalog));
    public static string Tooltip_PickMode => Get(nameof(Tooltip_PickMode));
    public static string Tooltip_ZoomIn => Get(nameof(Tooltip_ZoomIn));
    public static string Tooltip_ZoomOut => Get(nameof(Tooltip_ZoomOut));
    public static string Tooltip_ZoomToExtent => Get(nameof(Tooltip_ZoomToExtent));
    public static string Tooltip_ClosePickPanel => Get(nameof(Tooltip_ClosePickPanel));
    public static string Tooltip_SelectHit => Get(nameof(Tooltip_SelectHit));
    public static string Tooltip_FollowReference => Get(nameof(Tooltip_FollowReference));
    public static string Tooltip_CloseTimelinePanel => Get(nameof(Tooltip_CloseTimelinePanel));
    public static string Tooltip_AddFeatureCatalogue => Get(nameof(Tooltip_AddFeatureCatalogue));
    public static string Tooltip_AddPortrayalCatalogue => Get(nameof(Tooltip_AddPortrayalCatalogue));
    public static string Tooltip_OpenDataset => Get(nameof(Tooltip_OpenDataset));
    public static string Tooltip_RemoveCatalogue => Get(nameof(Tooltip_RemoveCatalogue));
    public static string Tooltip_RemoveDataset => Get(nameof(Tooltip_RemoveDataset));
    public static string Tooltip_ToggleDatasetVisibility => Get(nameof(Tooltip_ToggleDatasetVisibility));
    public static string Tooltip_DatasetOpacity => Get(nameof(Tooltip_DatasetOpacity));
    public static string Tooltip_MoveDatasetUp => Get(nameof(Tooltip_MoveDatasetUp));
    public static string Tooltip_MoveDatasetDown => Get(nameof(Tooltip_MoveDatasetDown));
    public static string Menu_BringDatasetToFront => Get(nameof(Menu_BringDatasetToFront));
    public static string Menu_SendDatasetToBack => Get(nameof(Menu_SendDatasetToBack));
    public static string Menu_MoveDatasetUp => Get(nameof(Menu_MoveDatasetUp));
    public static string Menu_MoveDatasetDown => Get(nameof(Menu_MoveDatasetDown));
    public static string SubLayer_S111_ColorBand => Get(nameof(SubLayer_S111_ColorBand));
    public static string SubLayer_S111_Arrows => Get(nameof(SubLayer_S111_Arrows));
    public static string Tooltip_ToggleSubLayerVisibility => Get(nameof(Tooltip_ToggleSubLayerVisibility));
    public static string Tooltip_SubLayerOpacity => Get(nameof(Tooltip_SubLayerOpacity));
    public static string Tooltip_ExpandSubLayers => Get(nameof(Tooltip_ExpandSubLayers));
    public static string Pane_SubLayers => Get(nameof(Pane_SubLayers));
    public static string Tooltip_ShowAllDatasets => Get(nameof(Tooltip_ShowAllDatasets));
    public static string Tooltip_HideAllDatasets => Get(nameof(Tooltip_HideAllDatasets));
    public static string Menu_IsolateDataset => Get(nameof(Menu_IsolateDataset));
    public static string Tooltip_ResetDatasetOpacity => Get(nameof(Tooltip_ResetDatasetOpacity));
    public static string Tooltip_TimelineSlider => Get(nameof(Tooltip_TimelineSlider));
    public static string Tooltip_TimelinePreviousStep => Get(nameof(Tooltip_TimelinePreviousStep));
    public static string Tooltip_TimelineNextStep => Get(nameof(Tooltip_TimelineNextStep));
    public static string Tooltip_MouseLatLon => Get(nameof(Tooltip_MouseLatLon));

    // Buttons / actions
    public static string Button_OpenDataset => Get(nameof(Button_OpenDataset));
    public static string Button_AddFeatureCatalogue => Get(nameof(Button_AddFeatureCatalogue));
    public static string Button_AddPortrayalCatalogue => Get(nameof(Button_AddPortrayalCatalogue));

    // Native menu
    public static string Menu_File => Get(nameof(Menu_File));
    public static string Menu_OpenDataset => Get(nameof(Menu_OpenDataset));
    public static string Menu_OpenRecent => Get(nameof(Menu_OpenRecent));
    public static string Menu_NoRecentDatasets => Get(nameof(Menu_NoRecentDatasets));
    public static string Menu_ClearRecentlyOpened => Get(nameof(Menu_ClearRecentlyOpened));
    public static string Menu_View => Get(nameof(Menu_View));
    public static string Menu_Appearance => Get(nameof(Menu_Appearance));
    public static string Menu_PrimarySideBar => Get(nameof(Menu_PrimarySideBar));
    public static string Menu_StatusBar => Get(nameof(Menu_StatusBar));
    public static string Menu_Timeline => Get(nameof(Menu_Timeline));
    public static string Menu_PickReport => Get(nameof(Menu_PickReport));
    public static string Menu_PickMode => Get(nameof(Menu_PickMode));

    // File picker
    public static string FilePicker_OpenDatasetTitle => Get(nameof(FilePicker_OpenDatasetTitle));
    public static string FilePicker_S100DatasetsType => Get(nameof(FilePicker_S100DatasetsType));

    // Catalogue list
    public static string Catalogue_BuiltInLabel => Get(nameof(Catalogue_BuiltInLabel));

    // Catalog (S-128) panel
    public static string Catalog_EmptyMessage => Get(nameof(Catalog_EmptyMessage));
    public static string Catalog_SelectEntryPlaceholder => Get(nameof(Catalog_SelectEntryPlaceholder));
    public static string Catalog_NotForNavigation => Get(nameof(Catalog_NotForNavigation));
    public static string Catalog_Field_Spec => Get(nameof(Catalog_Field_Spec));
    public static string Catalog_Field_Edition => Get(nameof(Catalog_Field_Edition));
    public static string Catalog_Field_Update => Get(nameof(Catalog_Field_Update));
    public static string Catalog_Field_Issued => Get(nameof(Catalog_Field_Issued));
    public static string Catalog_Field_Updated => Get(nameof(Catalog_Field_Updated));
    public static string Catalog_Field_Coverage => Get(nameof(Catalog_Field_Coverage));
    public static string Catalog_Field_NorthEast => Get(nameof(Catalog_Field_NorthEast));
    public static string Catalog_Field_SouthWest => Get(nameof(Catalog_Field_SouthWest));
    public static string Catalog_SourceProperties => Get(nameof(Catalog_SourceProperties));

    // Pick (Object Information) panel
    public static string Pick_PanelTitle => Get(nameof(Pick_PanelTitle));
    public static string Pick_IdLabel => Get(nameof(Pick_IdLabel));
    public static string Pick_SpecFormat => Get(nameof(Pick_SpecFormat));
    public static string Pick_SourceFormat => Get(nameof(Pick_SourceFormat));
    public static string Pick_AttributesHeading => Get(nameof(Pick_AttributesHeading));
    public static string Pick_NoAttributes => Get(nameof(Pick_NoAttributes));
    public static string Pick_HitListHeader => Get(nameof(Pick_HitListHeader));
    public static string Pick_HitListItemFormat => Get(nameof(Pick_HitListItemFormat));
    public static string Pick_ReferencesHeader => Get(nameof(Pick_ReferencesHeader));
    public static string Pick_ReferenceItemFormat => Get(nameof(Pick_ReferenceItemFormat));

    // Settings
    public static string Settings_Heading => Get(nameof(Settings_Heading));
    public static string Settings_AccentColor => Get(nameof(Settings_AccentColor));
    public static string Settings_ColorProfile => Get(nameof(Settings_ColorProfile));
    public static string Settings_ColorProfile_Help => Get(nameof(Settings_ColorProfile_Help));
    public static string Settings_SymbolScale => Get(nameof(Settings_SymbolScale));
    public static string Settings_SymbolScale_Help => Get(nameof(Settings_SymbolScale_Help));
    public static string Settings_TextScale => Get(nameof(Settings_TextScale));
    public static string Settings_TextScale_Help => Get(nameof(Settings_TextScale_Help));
    public static string Settings_DistanceUnits => Get(nameof(Settings_DistanceUnits));
    public static string Settings_DistanceUnits_Help => Get(nameof(Settings_DistanceUnits_Help));

    // Distance unit display names
    public static string DistanceUnit_Metric => Get(nameof(DistanceUnit_Metric));
    public static string DistanceUnit_Miles => Get(nameof(DistanceUnit_Miles));
    public static string DistanceUnit_NauticalMiles => Get(nameof(DistanceUnit_NauticalMiles));

    // Palette display names
    public static string Palette_Day => Get(nameof(Palette_Day));
    public static string Palette_Dusk => Get(nameof(Palette_Dusk));
    public static string Palette_Night => Get(nameof(Palette_Night));

    // Status messages
    public static string Status_UnrecognizedFileType => Get(nameof(Status_UnrecognizedFileType));
    public static string Status_SelectPortrayalCatalogue => Get(nameof(Status_SelectPortrayalCatalogue));
    public static string Status_LoadingFile => Get(nameof(Status_LoadingFile));
    public static string Status_Error => Get(nameof(Status_Error));
    public static string Status_RenderingTimeStep => Get(nameof(Status_RenderingTimeStep));
    public static string Status_RenderingAtTime => Get(nameof(Status_RenderingAtTime));
    public static string Status_SwitchingPalette => Get(nameof(Status_SwitchingPalette));
    public static string Status_PaletteApplied => Get(nameof(Status_PaletteApplied));
    public static string Status_FeatureNoDetails => Get(nameof(Status_FeatureNoDetails));
    public static string Status_FeatureSummary => Get(nameof(Status_FeatureSummary));
    public static string Status_FeatureSummaryWithMore => Get(nameof(Status_FeatureSummaryWithMore));
    public static string Status_FeatureRefNotFound => Get(nameof(Status_FeatureRefNotFound));
    public static string Status_FileNoLongerExists => Get(nameof(Status_FileNoLongerExists));

    // Dataset entry
    public static string DatasetEntry_CurrentTimeFormat => Get(nameof(DatasetEntry_CurrentTimeFormat));

    // Timeline panel
    public static string TimelinePanel_Title => Get(nameof(TimelinePanel_Title));
    public static string TimelinePanel_Range => Get(nameof(TimelinePanel_Range));
    public static string TimelinePanel_NoData => Get(nameof(TimelinePanel_NoData));
    public static string TimelinePanel_EmptyTitle => Get(nameof(TimelinePanel_EmptyTitle));
    public static string TimelinePanel_EmptyDescription => Get(nameof(TimelinePanel_EmptyDescription));

    // Measure Mode
    public static string Tooltip_MeasureMode => Get(nameof(Tooltip_MeasureMode));
    public static string Menu_MeasureMode => Get(nameof(Menu_MeasureMode));
    public static string Status_MeasureLeg => Get(nameof(Status_MeasureLeg));
    public static string Status_MeasureTotal => Get(nameof(Status_MeasureTotal));
    public static string Status_MeasureNoData => Get(nameof(Status_MeasureNoData));
    public static string Status_MeasureLegLabel => Get(nameof(Status_MeasureLegLabel));
}
