using System.ComponentModel;
using Spectre.Console;
using Spectre.Console.Cli;

namespace EncDotNet.S100.PerfReport;

/// <summary>
/// The <c>summarise</c> command: reads a single <c>.jsonl</c> file and
/// prints a markdown summary of spans and metrics.
/// </summary>
public sealed class SummariseCommand : Command<SummariseCommand.Settings>
{
    public sealed class Settings : CommandSettings
    {
        [CommandArgument(0, "<FILE>")]
        [Description("Path to the .jsonl telemetry file.")]
        public string File { get; set; } = "";

        [CommandOption("--out <PATH>")]
        [Description("Write the summary to a markdown file instead of stdout.")]
        public string? OutputPath { get; set; }
    }

    public override int Execute(CommandContext context, Settings settings)
    {
        if (!System.IO.File.Exists(settings.File))
        {
            AnsiConsole.MarkupLine($"[red]File not found:[/] {settings.File}");
            return 1;
        }

        var data = TelemetryFileReader.Read(settings.File);
        var writer = settings.OutputPath is not null
            ? new StreamWriter(settings.OutputPath)
            : new StreamWriter(Console.OpenStandardOutput());

        try
        {
            WriteSummary(writer, data, settings.File);
        }
        finally
        {
            if (settings.OutputPath is not null) writer.Dispose();
        }

        if (settings.OutputPath is not null)
            AnsiConsole.MarkupLine($"[green]Summary written to:[/] {settings.OutputPath}");

        return 0;
    }

    internal static void WriteSummary(TextWriter writer, TelemetryFileReader data, string sourcePath)
    {
        writer.WriteLine($"# Telemetry Summary");
        writer.WriteLine();
        writer.WriteLine($"**Source:** `{Path.GetFileName(sourcePath)}`");
        writer.WriteLine($"**Spans:** {data.Spans.Count}  **Metrics:** {data.Metrics.Count}");
        writer.WriteLine();

        // Top spans by total duration.
        if (data.Spans.Count > 0)
        {
            writer.WriteLine("## Top spans by duration");
            writer.WriteLine();
            writer.WriteLine("| Span | Count | Total (ms) | Mean (ms) | Max (ms) |");
            writer.WriteLine("|------|-------|------------|-----------|----------|");

            var grouped = data.Spans
                .GroupBy(s => s.Name)
                .Select(g => new
                {
                    Name = g.Key,
                    Count = g.Count(),
                    Total = g.Sum(s => s.DurationMs),
                    Mean = g.Average(s => s.DurationMs),
                    Max = g.Max(s => s.DurationMs),
                })
                .OrderByDescending(x => x.Total)
                .Take(20);

            foreach (var row in grouped)
            {
                writer.WriteLine($"| {row.Name} | {row.Count} | {row.Total:F2} | {row.Mean:F2} | {row.Max:F2} |");
            }

            writer.WriteLine();
        }

        // Metrics.
        if (data.Metrics.Count > 0)
        {
            writer.WriteLine("## Metrics");
            writer.WriteLine();

            // Histograms.
            var histograms = data.Metrics.Where(m => m.Instrument == "histogram").ToList();
            if (histograms.Count > 0)
            {
                writer.WriteLine("### Histograms");
                writer.WriteLine();
                writer.WriteLine("| Name | Unit | Count | Sum | Min | Max |");
                writer.WriteLine("|------|------|-------|-----|-----|-----|");

                foreach (var h in histograms.OrderBy(m => m.Name))
                {
                    writer.WriteLine($"| {h.Name} | {h.Unit ?? "-"} | {h.BucketCount?.ToString() ?? "-"} | {h.BucketSum?.ToString("F2") ?? "-"} | {h.BucketMin?.ToString("F2") ?? "-"} | {h.BucketMax?.ToString("F2") ?? "-"} |");
                }

                writer.WriteLine();
            }

            // Counters.
            var counters = data.Metrics.Where(m => m.Instrument == "counter").ToList();
            if (counters.Count > 0)
            {
                writer.WriteLine("### Counters");
                writer.WriteLine();
                writer.WriteLine("| Name | Unit | Value |");
                writer.WriteLine("|------|------|-------|");

                foreach (var c in counters.OrderBy(m => m.Name))
                {
                    writer.WriteLine($"| {c.Name} | {c.Unit ?? "-"} | {c.Value?.ToString("F0") ?? "-"} |");
                }

                writer.WriteLine();
            }
        }

        writer.WriteLine("---");
        writer.WriteLine("*Generated by EncDotNet.S100.PerfReport*");
        writer.Flush();
    }
}
