
-- ISSUES: PSWG #49, PC #112

-- Signal Station Warning main entry point.
function SignalStationWarning(feature, featurePortrayal, contextParameters)
	local viewingGroup

	-- NOTE: rearranged and not autogenerated 

	viewingGroup = 28020
	if contextParameters.RadarOverlay then
		featurePortrayal:AddInstructions('ViewingGroup:28020;DrawingPriority:21;DisplayPlane:OverRADAR')
	else
		featurePortrayal:AddInstructions('ViewingGroup:28020;DrawingPriority:21;DisplayPlane:UnderRADAR')
	end

	if feature.PrimitiveType == PrimitiveType.Point then
		-- Simplified and paper chart points use the same symbolization		
		if contains(15, feature.categoryOfSignalStationWarning) then
			featurePortrayal:AddInstructions('PointInstruction:WTLVGG02') 
        elseif contains(16, feature.categoryOfSignalStationWarning) then
           	featurePortrayal:AddInstructions('PointInstruction:VTCLMK01') 
		elseif contains(18, feature.categoryOfSignalStationWarning) then
			featurePortrayal:AddInstructions('PointInstruction:HGWTMK01') 
        else
           	featurePortrayal:AddInstructions('PointInstruction:SISTAW03') 
        end
	elseif feature.PrimitiveType == PrimitiveType.Surface then
		-- PSWG #49
		viewingGroup = 28020
		featurePortrayal:AddInstructions('ViewingGroup:28020;DrawingPriority:21;PointInstruction:SISTAW03')
	else
		error('Invalid primitive type or mariner settings passed to portrayal')
	end

	return viewingGroup
end
