
-- Signal Station Traffic main entry point.
function SignalStationTraffic(feature, featurePortrayal, contextParameters)
	local viewingGroup

	-- NOTE: rearranged and not autogenerated for #48 
	viewingGroup = 28020
	if contextParameters.RadarOverlay then
		featurePortrayal:AddInstructions('ViewingGroup:28020;DrawingPriority:21;DisplayPlane:OverRADAR')
	else
		featurePortrayal:AddInstructions('ViewingGroup:28020;DrawingPriority:21;DisplayPlane:UnderRADAR')
	end


	if feature.PrimitiveType == PrimitiveType.Point then
		-- Simplified and paper chart points use the same symbolization
		if contains(2, feature.categoryOfSignalStationTraffic) then
			featurePortrayal:AddInstructions('PointInstruction:SSENTR01') 
		elseif contains(6, feature.categoryOfSignalStationTraffic) then
			featurePortrayal:AddInstructions('PointInstruction:SSLOCK01') 
		elseif contains(10, feature.categoryOfSignalStationTraffic) then
			featurePortrayal:AddInstructions('PointInstruction:SSWARS01') 
	   	else
			featurePortrayal:AddInstructions('PointInstruction:SISTAT03') 
	   	end
	elseif feature.PrimitiveType == PrimitiveType.Surface then
		-- PSWG #48
		viewingGroup = 28020
		featurePortrayal:AddInstructions('ViewingGroup:28020;DrawingPriority:21;PointInstruction:SISTAT03')
	else
		error('Invalid primitive type or mariner settings passed to portrayal')
	end

	return viewingGroup
end
